Андрей Усачев ОЭМИб-ПИ01-20-2
IHVH/OEMIB_PI01_19_TBOT pull request #113
Opened 2023-05-29 16:58 UTC by Bogpiva

Random User

2023-06-02 07:47 UTC, IHVH requested changes
Подойдёт, было уже в части с discord, но здесь не было так что нормально. 
Уберите только пожалуйста src в файле random_fox

2023-06-02 07:47 UTC, IHVH commented on src/functions/random_fox.py
> +from src.bot_func_abc import BotFunctionABC
убрать src

2023-06-04 19:33 UTC, Bogpiva commented on src/functions/random_fox.py
> +from src.bot_func_abc import BotFunctionABC
Исправил

2023-06-09 08:14 UTC, IHVH approved these changes
Ок!

2023-06-09 08:14 UTC, merged