random dog photo
IHVH/OEMIB_PI01_19_TBOT pull request #51
Opened 2023-03-30 18:58 UTC by may-uri

tabunov ОЭМИб-ПИ01-20-2

2023-03-30 19:41 UTC, IHVH requested changes
Перенесите пожалуйста информацию о вашей функции в существующий файл /src/bot_func_dictionary.py

2023-03-30 19:58 UTC, may-uri commented
готово?

2023-03-31 09:01 UTC, IHVH requested changes
Необходимо этот файл [bot_func_dictionary.py](https://github.com/may-uri/OEMIB_PI01_19_TBOT/blob/may-uri-patch-2/bot_func_dictionary.py) который в корне удалить. 
А информацию о функции внести в файл  [bot_func_dictionary.py](https://github.com/may-uri/OEMIB_PI01_19_TBOT/blob/may-uri-patch-2/src/bot_func_dictionary.py) который в директории src

2023-03-31 09:08 UTC, IHVH approved these changes
Ok

2023-03-31 09:08 UTC, merged