SteamStatus
IHVH/OEMIB_PI01_19_TBOT pull request #82
Opened 2023-05-14 14:42 UTC by eldorPulatov

2023-05-14 22:10 UTC, IHVH commented
Добрый вечер. Помимо проверки статуса ответа необходимо получить и обработать какие-нибудь данные с удаленного сервера, ещё лучше использовать какой-нибудь программный интерфейс (api) для этого.

2023-05-14 22:18 UTC, eldorPulatov commented
Пулатов Э.К.

2023-05-14 23:08 UTC, eldorPulatov commented
Переделал работу, беру данные из NYTimes.

2023-05-15 10:02 UTC, IHVH requested changes
Также необходимо добавить информацию о вашей функции в [bot_func_dictionary.py](https://github.com/IHVH/OEMIB_PI01_19_TBOT/blob/main/src/bot_func_dictionary.py)

2023-05-15 10:27 UTC, eldorPulatov commented on src/functions/NYTimes.py
> +        self.api_key = "JOv1U7L6ISqj8jAWPIS3SUHAv33sNfEn"
Как правильно добавить данные в bot_func_dictonary? Я добавлял данные схожие с выше стоящими, но тесты не проходят

2023-05-15 10:32 UTC, IHVH commented on src/functions/NYTimes.py
> +        self.api_key = "JOv1U7L6ISqj8jAWPIS3SUHAv33sNfEn"
Там у Вас ошибка синтаксиса была. 
По моему запятая пропущена

2023-05-15 10:34 UTC, IHVH commented on src/functions/NYTimes.py
> +        self.api_key = "JOv1U7L6ISqj8jAWPIS3SUHAv33sNfEn"
![image](https://github.com/IHVH/OEMIB_PI01_19_TBOT/assets/6233983/0f89e7a5-2381-4000-a883-3a7b9c3092e9)

2023-05-15 10:42 UTC, IHVH approved these changes
Ок!

2023-05-15 10:45 UTC, merged