Тищенко Леонид ОЭМИБ-ПИ01-20-2
IHVH/OEMIB_PI01_19_TBOT pull request #85
Opened 2023-05-16 16:28 UTC by Leonnid111

2023-05-16 17:05 UTC, IHVH requested changes

2023-05-16 17:05 UTC, IHVH commented on src/bot_func_dictionary.py
> +    bot_function = Lenta_news(),
Необходимо добавить импорт

2023-05-16 17:15 UTC, Leonnid111 commented
> Добрый день. Парсинг страницы не самый лучший вариант. Если есть общедоступный программный интерфейс (api) постарайтесь его использовать.

Эта функция не подойдет?

2023-05-16 18:30 UTC, Leonnid111 commented on src/bot_func_dictionary.py
> +    bot_function = Lenta_news(),
Эта не подойдет?

2023-05-16 18:34 UTC, Leonnid111 commented on src/bot_func_dictionary.py
> +    bot_function = Lenta_news(),
добавил

2023-05-17 08:20 UTC, IHVH commented on src/bot_func_dictionary.py
> +    bot_function = Lenta_news(),
??

2023-05-17 20:50 UTC, Leonnid111 commented on src/bot_func_dictionary.py
> +    bot_function = Lenta_news(),
Добавил нового про чак норриса

2023-05-17 21:34 UTC, IHVH approved these changes

2023-05-17 21:36 UTC, merged